import Head from 'next/head';
import CommentModal from '../../components/CommentModal';
import Sidebar from '../../components/Sidebar';
import Widgets from '../../components/Widgets';
import Post from '../../components/Post';
import { useRouter } from 'next/router';
import { ArrowLeftIcon } from '@heroicons/react/outline';
import { useEffect, useState } from 'react';
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore';
import { db } from '../../firebase';
import { comment } from 'postcss';
import Comment from '../../components/Comment';

export default function PostPage({newResults, randomUsersResults}) {
    const router = useRouter();
    const { id } = router.query;
    const [post, setPost] = useState();
    const [comments, setComments] = useState([]);

    useEffect(() => {
        onSnapshot(doc(db, 'posts', id), (snapshot) => setPost(snapshot));
    }, [db, id]);

    useEffect(() => {
        const unsubscribe = onSnapshot(
            query(
                collection(db, 'posts', id, 'comments'),
                orderBy('timestamp', 'desc')
            )
            , (snapshot) => setComments(snapshot.docs)
        )
    }, [db, id]);

  return (
    <div>
      <Head>
        <title>post page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen mx-auto'>
        <Sidebar />


        <div className="xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
            <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200 ">
                <div onClick={() => router.push('/')} className='hoverEffect flex items-center justify-center'>
                    <ArrowLeftIcon className='h-5'/>
                </div>
                <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
                    Tweet
                </h2>
            </div>
            <Post id={id} post={post} />
            <div className=''>
                {comments.map((comment) => 
                    <Comment key={comment.id} id={comment.id} comment={comment.data()} />
                )}
            </div>
        </div>


        <Widgets newResults={newResults.articles} randomUsersResults={randomUsersResults.results} />
        <CommentModal />
      </main>
    </div>
  )
}



export async function getServerSideProps() {
  const newResults = await fetch(
    'https://saurav.tech/NewsAPI/top-headlines/category/business/in.json'
  ).then((res=>res.json()));

  //who to follow section
  const randomUsersResults = await fetch(
    'https://randomuser.me/api/?results=30&inc=name,login,picture'
  ).then((res=>res.json()));

  return {
    props: {
      newResults,
      randomUsersResults
    }
  }
}